"""Build deep Factory-derived velocity semantic profiles (NO DNA).

Input: factory_records.ndjson generated by the tolerant Factory parser.
Output: pa800_optimizer/profiles/data/factory_velocity_semantics_v2.json

The data is empirical only. It does not assign RX/DNC articulation names.
"""
from __future__ import annotations
import argparse, collections, json, math, statistics
from pathlib import Path
try:
    import orjson
    loads = orjson.loads
except Exception:
    loads = json.loads


def q_hist(hist, p):
    n = sum(hist)
    if not n:
        return None
    pos = (n - 1) * p
    lo, hi = math.floor(pos), math.ceil(pos)
    def kth(k):
        s = 0
        for i, c in enumerate(hist):
            s += c
            if s > k:
                return i
        return 127
    a, b = kth(lo), kth(hi)
    return float(a) if lo == hi else a * (hi - pos) + b * (pos - lo)


def robust_summary(hist):
    if not sum(hist):
        return None
    return {k: round(q_hist(hist, p), 3) for k, p in (
        ('raw_min', 0), ('p01', .01), ('p05', .05), ('working_min', .10),
        ('ideal_min', .25), ('ideal_center', .50), ('ideal_max', .75),
        ('working_max', .90), ('p95', .95), ('p99', .99), ('raw_max', 1),
    )}


def smooth(hist):
    w = [1,2,3,2,1]
    out = [0.0]*128
    for i in range(1,128):
        num = den = 0.0
        for off, ww in zip(range(-2,3), w):
            j = i + off
            if 1 <= j <= 127:
                num += hist[j] * ww
                den += ww
        out[i] = num/den if den else 0.0
    return out


def modes_and_valleys(hist):
    n = sum(hist)
    if n < 30:
        return [], []
    sm = smooth(hist)
    minheight = max(2.0, n * .0025)
    peaks = []
    for i in range(2,127):
        if sm[i] >= sm[i-1] and sm[i] >= sm[i+1] and sm[i] >= minheight:
            peaks.append((sm[i], i))
    peaks.sort(reverse=True)
    chosen = []
    for h, i in peaks:
        if all(abs(i-j) >= 5 for _,j in chosen):
            chosen.append((h,i))
        if len(chosen) >= 6:
            break
    chosen = sorted(chosen, key=lambda x:x[1])
    modes = []
    for h, i in chosen:
        lo = max(1, i-4); hi = min(127, i+4)
        support = sum(hist[lo:hi+1])
        modes.append({'center': i, 'local_support': support, 'fraction': round(support/n, 6)})
    valleys = []
    for (_,a),(_,b) in zip(chosen, chosen[1:]):
        if b-a < 3:
            continue
        v = min(range(a+1,b), key=lambda x: sm[x])
        depth = 1.0 - (sm[v] / max(1e-9, min(sm[a], sm[b])))
        valleys.append({'velocity': v, 'depth': round(depth, 5), 'left_mode': a, 'right_mode': b})
    return modes, valleys


def grade(n, styles):
    if n >= 1000 and styles >= 10: return 'STRONG'
    if n >= 300 and styles >= 5: return 'GOOD'
    if n >= 100 and styles >= 3: return 'LIMITED'
    return 'WEAK'


class Agg:
    __slots__ = ('hist','notes','styles','pitch_vel','beat_vel','delta_hist','repeat_delta_hist','last_by_segment','fileseg')
    def __init__(self):
        self.hist = [0]*128
        self.notes = 0
        self.styles = set()
        self.pitch_vel = collections.defaultdict(lambda:[0]*128)
        self.beat_vel = collections.defaultdict(lambda:[0]*128)
        # velocity delta [-126..126] => index +126
        self.delta_hist = [0]*253
        self.repeat_delta_hist = [0]*253
        self.last_by_segment = {}
        self.fileseg = set()
    def add(self, r, key_tag):
        v = int(r['velocity']); p = int(r['note'])
        if not 1 <= v <= 127:
            return
        self.hist[v] += 1; self.notes += 1; self.styles.add(r['file'])
        self.pitch_vel[p][v] += 1
        ppq = max(1, int(r.get('ppq') or 192)); tsn=int(r.get('ts_num') or 4); tsd=int(r.get('ts_den') or 4)
        beat_ticks = ppq*4.0/tsd
        bar_ticks = beat_ticks*tsn
        rel = int(r.get('rel_onset') or 0)
        within = rel % max(1,int(round(bar_ticks)))
        sixteenth = ppq/4.0
        pos16 = int(round(within/sixteenth)) if sixteenth else 0
        beat_key = f'{tsn}/{tsd}:{pos16}'
        self.beat_vel[beat_key][v] += 1
        seg=(r['file'],r['track'],r.get('element'),r.get('cv'),r.get('msb'),r.get('lsb'),r.get('program'),r.get('sound'))
        self.fileseg.add(seg)
        prev = self.last_by_segment.get(seg)
        onset = int(r.get('rel_onset') or 0)
        if prev is not None and onset > prev[0]:
            d = max(-126,min(126,v-prev[2])); self.delta_hist[d+126]+=1
            if p == prev[1]: self.repeat_delta_hist[d+126]+=1
        # only replace state when distinct onset, so simultaneous chord notes don't form fake sequence
        if prev is None or onset > prev[0]:
            self.last_by_segment[seg]=(onset,p,v)


def sparse_conditional(counter, min_n=30):
    out={}
    for k,h in counter.items():
        n=sum(h)
        if n < min_n: continue
        modes,valleys=modes_and_valleys(h)
        out[str(k)]={'n':n,'summary':robust_summary(h),'histogram_1_127':h[1:], 'modes':modes,'valleys':valleys}
    return out


def delta_summary(hist):
    n=sum(hist)
    if not n:return None
    vals=[]
    # quantiles from histogram in delta domain
    def q(p):
        target=(n-1)*p; lo=math.floor(target); hi=math.ceil(target)
        def kth(k):
            s=0
            for i,c in enumerate(hist):
                s+=c
                if s>k:return i-126
            return 126
        a,b=kth(lo),kth(hi)
        return a if lo==hi else a*(hi-target)+b*(target-lo)
    mean=sum((i-126)*c for i,c in enumerate(hist))/n
    var=sum((((i-126)-mean)**2)*c for i,c in enumerate(hist))/n
    return {'n':n,'p10':round(q(.1),3),'p25':round(q(.25),3),'p50':round(q(.5),3),'p75':round(q(.75),3),'p90':round(q(.9),3),'mean':round(mean,3),'std':round(math.sqrt(var),3),'histogram_delta_-126_126':hist}


def pack(key, a, include_conditionals=True):
    modes,valleys=modes_and_valleys(a.hist)
    p={
      'key': key,
      'support':{'notes':a.notes,'styles':len(a.styles),'segments':len(a.fileseg),'grade':grade(a.notes,len(a.styles))},
      'velocity':robust_summary(a.hist),
      'histogram_1_127':a.hist[1:],
      'modes':modes,
      'valleys':valleys,
      'sequence_delta':delta_summary(a.delta_hist),
      'repeated_pitch_delta':delta_summary(a.repeat_delta_hist),
    }
    if include_conditionals:
        p['pitch_velocity']=sparse_conditional(a.pitch_vel, min_n=30)
        p['beat_velocity']=sparse_conditional(a.beat_vel, min_n=30)
    return p


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--records',default='/mnt/data/factory_records.ndjson')
    ap.add_argument('--out',default=str(Path(__file__).resolve().parents[2]/'pa800_optimizer/profiles/data/factory_velocity_semantics_v2.json'))
    args=ap.parse_args()
    parents=collections.defaultdict(Agg)
    contexts=collections.defaultdict(Agg)
    with open(args.records,'rb') as f:
        for line in f:
            r=loads(line)
            if not r.get('sound') or r.get('msb') is None or r.get('lsb') is None or r.get('program') is None:
                continue
            pk=(int(r['msb']),int(r['lsb']),int(r['program']),str(r['sound']))
            ck=pk+(str(r.get('role') or 'UNKNOWN'),str(r.get('element') or 'UNKNOWN'),int(r.get('cv') or 0))
            parents[pk].add(r,pk); contexts[ck].add(r,ck)
    parent_profiles=[]
    for k,a in parents.items():
        parent_profiles.append(pack({'msb':k[0],'lsb':k[1],'program':k[2],'sound':k[3]},a,True))
    context_profiles=[]
    for k,a in contexts.items():
        if a.notes < 30: continue
        context_profiles.append(pack({'msb':k[0],'lsb':k[1],'program':k[2],'sound':k[3],'role':k[4],'element':k[5],'cv':k[6]},a,False))
    parent_profiles.sort(key=lambda x:x['support']['notes'],reverse=True)
    context_profiles.sort(key=lambda x:x['support']['notes'],reverse=True)
    out={'schema':'PA800_FACTORY_VELOCITY_SEMANTICS_V2','source':'Factory Styles.zip','parent_profiles':parent_profiles,'context_profiles':context_profiles,
         'rules':{'raw_min_max_are_observations':True,'histogram_domain':'1..127','context_key':'address+sound+role+element+cv','semantic_labels_from_factory_only':False}}
    op=Path(args.out);op.parent.mkdir(parents=True,exist_ok=True)
    op.write_text(json.dumps(out,separators=(',',':')),encoding='utf-8')
    print('parents',len(parent_profiles),'contexts',len(context_profiles),'bytes',op.stat().st_size)

if __name__=='__main__':main()